// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by the Game Data Editor.
//
//      Changes to this file will be lost if the code is regenerated.
//
//      This file was generated from this data file:
//      D:\UnityProjectsGit\AZGame\AZGame\Assets/Packages/GameDataEditor/Resources/gde_data.txt
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System;
using System.Collections.Generic;

using GameDataEditor;

namespace GameDataEditor
{
    public class GDECharactersData : IGDEData
    {
        static string BasicMeleeKey = "BasicMelee";
		float _BasicMelee;
        public float BasicMelee
        {
            get { return _BasicMelee; }
            set {
                if (_BasicMelee != value)
                {
                    _BasicMelee = value;
					GDEDataManager.SetFloat(_key, BasicMeleeKey, _BasicMelee);
                }
            }
        }

        static string BasicDistanceKey = "BasicDistance";
		float _BasicDistance;
        public float BasicDistance
        {
            get { return _BasicDistance; }
            set {
                if (_BasicDistance != value)
                {
                    _BasicDistance = value;
					GDEDataManager.SetFloat(_key, BasicDistanceKey, _BasicDistance);
                }
            }
        }

        static string BasicMagicKey = "BasicMagic";
		float _BasicMagic;
        public float BasicMagic
        {
            get { return _BasicMagic; }
            set {
                if (_BasicMagic != value)
                {
                    _BasicMagic = value;
					GDEDataManager.SetFloat(_key, BasicMagicKey, _BasicMagic);
                }
            }
        }

        static string CharacterNameKey = "CharacterName";
		string _CharacterName;
        public string CharacterName
        {
            get { return _CharacterName; }
            set {
                if (_CharacterName != value)
                {
                    _CharacterName = value;
					GDEDataManager.SetString(_key, CharacterNameKey, _CharacterName);
                }
            }
        }

        static string CharacterDescriptionKey = "CharacterDescription";
		string _CharacterDescription;
        public string CharacterDescription
        {
            get { return _CharacterDescription; }
            set {
                if (_CharacterDescription != value)
                {
                    _CharacterDescription = value;
					GDEDataManager.SetString(_key, CharacterDescriptionKey, _CharacterDescription);
                }
            }
        }

        static string DifficultyLevelKey = "DifficultyLevel";
		string _DifficultyLevel;
        public string DifficultyLevel
        {
            get { return _DifficultyLevel; }
            set {
                if (_DifficultyLevel != value)
                {
                    _DifficultyLevel = value;
					GDEDataManager.SetString(_key, DifficultyLevelKey, _DifficultyLevel);
                }
            }
        }

        public GDECharactersData(string key) : base(key)
        {
            GDEDataManager.RegisterItem(this.SchemaName(), key);
        }
        public override Dictionary<string, object> SaveToDict()
		{
			var dict = new Dictionary<string, object>();
			dict.Add(GDMConstants.SchemaKey, "Characters");
			
            dict.Merge(true, BasicMelee.ToGDEDict(BasicMeleeKey));
            dict.Merge(true, BasicDistance.ToGDEDict(BasicDistanceKey));
            dict.Merge(true, BasicMagic.ToGDEDict(BasicMagicKey));
            dict.Merge(true, CharacterName.ToGDEDict(CharacterNameKey));
            dict.Merge(true, CharacterDescription.ToGDEDict(CharacterDescriptionKey));
            dict.Merge(true, DifficultyLevel.ToGDEDict(DifficultyLevelKey));
            return dict;
		}

        public override void UpdateCustomItems(bool rebuildKeyList)
        {
        }

        public override void LoadFromDict(string dataKey, Dictionary<string, object> dict)
        {
            _key = dataKey;

			if (dict == null)
				LoadFromSavedData(dataKey);
			else
			{
                dict.TryGetFloat(BasicMeleeKey, out _BasicMelee);
                dict.TryGetFloat(BasicDistanceKey, out _BasicDistance);
                dict.TryGetFloat(BasicMagicKey, out _BasicMagic);
                dict.TryGetString(CharacterNameKey, out _CharacterName);
                dict.TryGetString(CharacterDescriptionKey, out _CharacterDescription);
                dict.TryGetString(DifficultyLevelKey, out _DifficultyLevel);
                LoadFromSavedData(dataKey);
			}
		}

        public override void LoadFromSavedData(string dataKey)
		{
			_key = dataKey;
			
            _BasicMelee = GDEDataManager.GetFloat(_key, BasicMeleeKey, _BasicMelee);
            _BasicDistance = GDEDataManager.GetFloat(_key, BasicDistanceKey, _BasicDistance);
            _BasicMagic = GDEDataManager.GetFloat(_key, BasicMagicKey, _BasicMagic);
            _CharacterName = GDEDataManager.GetString(_key, CharacterNameKey, _CharacterName);
            _CharacterDescription = GDEDataManager.GetString(_key, CharacterDescriptionKey, _CharacterDescription);
            _DifficultyLevel = GDEDataManager.GetString(_key, DifficultyLevelKey, _DifficultyLevel);
        }

        public GDECharactersData ShallowClone()
		{
			string newKey = Guid.NewGuid().ToString();
			GDECharactersData newClone = new GDECharactersData(newKey);

            newClone.BasicMelee = BasicMelee;
            newClone.BasicDistance = BasicDistance;
            newClone.BasicMagic = BasicMagic;
            newClone.CharacterName = CharacterName;
            newClone.CharacterDescription = CharacterDescription;
            newClone.DifficultyLevel = DifficultyLevel;

            return newClone;
		}

        public GDECharactersData DeepClone()
		{
			GDECharactersData newClone = ShallowClone();
            return newClone;
		}

        public void Reset_BasicMelee()
        {
            GDEDataManager.ResetToDefault(_key, BasicMeleeKey);

            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            dict.TryGetFloat(BasicMeleeKey, out _BasicMelee);
        }

        public void Reset_BasicDistance()
        {
            GDEDataManager.ResetToDefault(_key, BasicDistanceKey);

            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            dict.TryGetFloat(BasicDistanceKey, out _BasicDistance);
        }

        public void Reset_BasicMagic()
        {
            GDEDataManager.ResetToDefault(_key, BasicMagicKey);

            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            dict.TryGetFloat(BasicMagicKey, out _BasicMagic);
        }

        public void Reset_CharacterName()
        {
            GDEDataManager.ResetToDefault(_key, CharacterNameKey);

            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            dict.TryGetString(CharacterNameKey, out _CharacterName);
        }

        public void Reset_CharacterDescription()
        {
            GDEDataManager.ResetToDefault(_key, CharacterDescriptionKey);

            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            dict.TryGetString(CharacterDescriptionKey, out _CharacterDescription);
        }

        public void Reset_DifficultyLevel()
        {
            GDEDataManager.ResetToDefault(_key, DifficultyLevelKey);

            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            dict.TryGetString(DifficultyLevelKey, out _DifficultyLevel);
        }

        public void ResetAll()
        {
            GDEDataManager.ResetToDefault(_key, CharacterNameKey);
            GDEDataManager.ResetToDefault(_key, CharacterDescriptionKey);
            GDEDataManager.ResetToDefault(_key, DifficultyLevelKey);
            GDEDataManager.ResetToDefault(_key, BasicMeleeKey);
            GDEDataManager.ResetToDefault(_key, BasicDistanceKey);
            GDEDataManager.ResetToDefault(_key, BasicMagicKey);


            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            LoadFromDict(_key, dict);
        }
    }
}
