// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by the Game Data Editor.
//
//      Changes to this file will be lost if the code is regenerated.
//
//      This file was generated from this data file:
//      D:\UnityProjectsGit\AZGame\AZGame\Assets/Packages/GameDataEditor/Resources/gde_data.txt
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System;

namespace GameDataEditor
{
    public partial class GDEItemKeys
    {
        public static string Characters_CH001 = "CH001";
        public static string Characters_CH002 = "CH002";
        public static string Characters_CH003 = "CH003";
        public static string Characters_CH004 = "CH004";
        public static string Characters_CH005 = "CH005";
        public static string Monsters_MO001 = "MO001";
        public static string Monsters_MO002 = "MO002";
        public static string Monsters_MO003 = "MO003";
        public static string Monsters_MO004 = "MO004";
        public static string Monsters_MO005 = "MO005";
        public static string Monsters_MO006 = "MO006";
        public static string Monsters_MO007 = "MO007";
        public static string Monsters_MO008 = "MO008";
        public static string Monsters_MO009 = "MO009";
        public static string Monsters_MO010 = "MO010";
        public static string Monsters_MO011 = "MO011";
        public static string Monsters_MO012 = "MO012";
        public static string Monsters_MO013 = "MO013";
        public static string Monsters_MO014 = "MO014";
        public static string Monsters_MO015 = "MO015";
        public static string Monsters_MO016 = "MO016";
        public static string Monsters_MO017 = "MO017";
        public static string Monsters_MO018 = "MO018";
        public static string Monsters_MO019 = "MO019";
        public static string Monsters_MO020 = "MO020";
        public static string Missions_M001 = "M001";
        public static string Missions_M0011 = "M0011";
        public static string Missions_M0012 = "M0012";
        public static string Missions_M0013 = "M0013";
        public static string Missions_M0014 = "M0014";
        public static string Missions_M002 = "M002";
    }
}
