// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by the Game Data Editor.
//
//      Changes to this file will be lost if the code is regenerated.
//
//      This file was generated from this data file:
//      D:\UnityProjectsGit\AZGame\AZGame\Assets/Packages/GameDataEditor/Resources/gde_data.txt
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System;

namespace GameDataEditor
{
    public partial class GDESchemaKeys
    {
        public static string Characters = "Characters";
        public static string Monsters = "Monsters";
        public static string Missions = "Missions";
    }
}
